"""Widen pe_firms.hq_country

Revision ID: 1e4c3f8c6a08
Revises: 68db917183b1
Create Date: 2026-02-15 16:13:52.253353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e4c3f8c6a08'
down_revision: Union[str, Sequence[str], None] = '68db917183b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pe_firms', 'hq_country',
               existing_type=sa.VARCHAR(length=2),
               type_=sa.String(length=255),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pe_firms', 'hq_country',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=2),
               existing_nullable=True)
    # ### end Alembic commands ###
