"""add_scoring_config_recommendations

Revision ID: 408bb192a7ba
Revises: 994a24fc74ad
Create Date: 2026-02-16 23:23:48.495733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '408bb192a7ba'
down_revision: Union[str, Sequence[str], None] = '994a24fc74ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_config_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulatory_change_id', sa.Integer(), nullable=False),
    sa.Column('config_target', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('current_value', sa.String(length=100), nullable=True),
    sa.Column('recommended_value', sa.String(length=100), nullable=True),
    sa.Column('sovereignty_relevant', sa.Boolean(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.String(length=100), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['regulatory_change_id'], ['regulatory_changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_config_recommendations_regulatory_change_id'), 'scoring_config_recommendations', ['regulatory_change_id'], unique=False)
    op.create_index(op.f('ix_scoring_config_recommendations_status'), 'scoring_config_recommendations', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_config_recommendations_status'), table_name='scoring_config_recommendations')
    op.drop_index(op.f('ix_scoring_config_recommendations_regulatory_change_id'), table_name='scoring_config_recommendations')
    op.drop_table('scoring_config_recommendations')
    # ### end Alembic commands ###
