"""Initial Postgres schema

Revision ID: 68db917183b1
Revises: 
Create Date: 2026-02-15 15:58:42.729344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68db917183b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('slack_enabled', sa.Boolean(), nullable=False),
    sa.Column('notify_funding', sa.Boolean(), nullable=False),
    sa.Column('notify_leadership', sa.Boolean(), nullable=False),
    sa.Column('notify_news', sa.Boolean(), nullable=False),
    sa.Column('notify_product', sa.Boolean(), nullable=False),
    sa.Column('digest_frequency', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_preferences_user_id'), 'alert_preferences', ['user_id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('companies_house_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('hq_address', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw_website_text', sa.Text(), nullable=True),
    sa.Column('semantic_enriched_at', sa.DateTime(), nullable=True),
    sa.Column('revenue_gbp', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_gbp', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_margin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('gross_margin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('revenue_growth', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('financial_year', sa.Integer(), nullable=True),
    sa.Column('market_share', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('competitor_count', sa.Integer(), nullable=True),
    sa.Column('market_growth_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('sic_codes', sa.JSON(), nullable=True),
    sa.Column('moat_type', sa.String(length=50), nullable=True),
    sa.Column('moat_score', sa.Integer(), nullable=True),
    sa.Column('moat_attributes', sa.JSON(), nullable=True),
    sa.Column('moat_analysis', sa.JSON(), nullable=True),
    sa.Column('tier', sa.Enum('TIER_1A', 'TIER_1B', 'TIER_2', 'WAITLIST', name='companytier'), nullable=True),
    sa.Column('discovered_via', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_moat_score_desc', 'companies', [sa.literal_column('moat_score DESC')], unique=False)
    op.create_index(op.f('ix_companies_companies_house_number'), 'companies', ['companies_house_number'], unique=True)
    op.create_index(op.f('ix_companies_moat_score'), 'companies', ['moat_score'], unique=False)
    op.create_index(op.f('ix_companies_registration_number'), 'companies', ['registration_number'], unique=False)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_tier'), 'companies', ['tier'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('linkedin_url', sa.String(length=500), nullable=True),
    sa.Column('contact_type', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('relationship_strength', sa.String(length=20), nullable=False),
    sa.Column('relationship_score', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_contact_date', sa.Date(), nullable=True),
    sa.Column('enrichment_data', sa.JSON(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('idx_contact_company', 'contacts', ['company_name'], unique=False)
    op.create_index('idx_contact_strength', 'contacts', ['relationship_strength'], unique=False)
    op.create_index('idx_contact_type', 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_company_name'), 'contacts', ['company_name'], unique=False)
    op.create_index(op.f('ix_contacts_full_name'), 'contacts', ['full_name'], unique=False)
    op.create_table('corporate_parents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('revenue_eur', sa.BigInteger(), nullable=True),
    sa.Column('market_cap_eur', sa.BigInteger(), nullable=True),
    sa.Column('ceo_name', sa.String(length=255), nullable=True),
    sa.Column('ceo_tenure_months', sa.Integer(), nullable=True),
    sa.Column('has_divested_before', sa.Boolean(), nullable=True),
    sa.Column('activist_pressure', sa.Boolean(), nullable=True),
    sa.Column('activist_investor', sa.String(length=255), nullable=True),
    sa.Column('last_strategic_review_date', sa.Date(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_probabilities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=False),
    sa.Column('target_company_name', sa.String(length=255), nullable=False),
    sa.Column('probability_score', sa.Integer(), nullable=True),
    sa.Column('probability_tier', sa.String(length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('signals', sa.JSON(), nullable=True),
    sa.Column('signal_seller_distress', sa.Boolean(), nullable=True),
    sa.Column('signal_advisor_engaged', sa.Boolean(), nullable=True),
    sa.Column('signal_management_changes', sa.Boolean(), nullable=True),
    sa.Column('signal_declining_growth', sa.Boolean(), nullable=True),
    sa.Column('signal_pe_sector_interest', sa.Boolean(), nullable=True),
    sa.Column('signal_carveout_potential', sa.Boolean(), nullable=True),
    sa.Column('expected_timeline', sa.String(length=50), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_probability_company', 'deal_probabilities', ['target_company_id'], unique=True)
    op.create_index('idx_probability_score', 'deal_probabilities', ['probability_score'], unique=False)
    op.create_index(op.f('ix_deal_probabilities_target_company_id'), 'deal_probabilities', ['target_company_id'], unique=False)
    op.create_table('market_metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('time_period', sa.String(length=7), nullable=False),
    sa.Column('deal_count', sa.Integer(), nullable=True),
    sa.Column('total_value_gbp', sa.BigInteger(), nullable=True),
    sa.Column('average_deal_size_gbp', sa.BigInteger(), nullable=True),
    sa.Column('median_ev_revenue', sa.Float(), nullable=True),
    sa.Column('median_ev_ebitda', sa.Float(), nullable=True),
    sa.Column('avg_ev_revenue', sa.Float(), nullable=True),
    sa.Column('avg_ev_ebitda', sa.Float(), nullable=True),
    sa.Column('min_ev_ebitda', sa.Float(), nullable=True),
    sa.Column('max_ev_ebitda', sa.Float(), nullable=True),
    sa.Column('avg_growth_rate', sa.Float(), nullable=True),
    sa.Column('avg_ebitda_margin', sa.Float(), nullable=True),
    sa.Column('deal_count_change_pct', sa.Float(), nullable=True),
    sa.Column('value_change_pct', sa.Float(), nullable=True),
    sa.Column('multiple_change_pct', sa.Float(), nullable=True),
    sa.Column('is_hot_sector', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_hot', 'market_metrics', ['is_hot_sector'], unique=False)
    op.create_index('idx_metrics_sector_period', 'market_metrics', ['sector', 'time_period'], unique=False)
    op.create_index(op.f('ix_market_metrics_sector'), 'market_metrics', ['sector'], unique=False)
    op.create_index(op.f('ix_market_metrics_time_period'), 'market_metrics', ['time_period'], unique=False)
    op.create_table('market_trends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trend_name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=False),
    sa.Column('trend_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.String(length=20), nullable=False),
    sa.Column('first_detected', sa.Date(), nullable=True),
    sa.Column('supporting_evidence', sa.JSON(), nullable=True),
    sa.Column('implications_for_thesis', sa.Text(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitoring_targets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('last_content_hash', sa.String(length=64), nullable=True),
    sa.Column('selector', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('check_frequency', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pe_firms',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hq_country', sa.String(length=2), nullable=True),
    sa.Column('aum_usd', sa.BigInteger(), nullable=True),
    sa.Column('fund_count', sa.Integer(), nullable=True),
    sa.Column('founding_year', sa.Integer(), nullable=True),
    sa.Column('typical_check_size_usd', sa.BigInteger(), nullable=True),
    sa.Column('investment_strategy', sa.String(length=100), nullable=True),
    sa.Column('sector_focus', sa.JSON(), nullable=True),
    sa.Column('geography_focus', sa.JSON(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pe_firms_name'), 'pe_firms', ['name'], unique=False)
    op.create_table('regulatory_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jurisdiction', sa.String(length=50), nullable=False),
    sa.Column('regulatory_body', sa.String(length=100), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affected_sectors', sa.JSON(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('creates_barriers_to_entry', sa.Boolean(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategic_acquirers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('revenue_usd', sa.BigInteger(), nullable=True),
    sa.Column('market_cap_usd', sa.BigInteger(), nullable=True),
    sa.Column('acquisition_budget_annual_usd', sa.BigInteger(), nullable=True),
    sa.Column('typical_multiple_paid', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('values_regulatory_moats', sa.Boolean(), nullable=True),
    sa.Column('values_network_effects', sa.Boolean(), nullable=True),
    sa.Column('acquisitions_last_24mo', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategic_acquirers_name'), 'strategic_acquirers', ['name'], unique=False)
    op.create_table('tracked_companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('tracking_status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('added_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_checked', sa.DateTime(), nullable=True),
    sa.Column('next_check_due', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tracked_status_priority', 'tracked_companies', ['tracking_status', 'priority'], unique=False)
    op.create_index(op.f('ix_tracked_companies_company_id'), 'tracked_companies', ['company_id'], unique=False)
    op.create_index(op.f('ix_tracked_companies_next_check_due'), 'tracked_companies', ['next_check_due'], unique=False)
    op.create_index(op.f('ix_tracked_companies_priority'), 'tracked_companies', ['priority'], unique=False)
    op.create_index(op.f('ix_tracked_companies_tracking_status'), 'tracked_companies', ['tracking_status'], unique=False)
    op.create_table('vc_firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('linkedin_company_id', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('focus_sectors', sa.Text(), nullable=True),
    sa.Column('typical_check_size_gbp', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vc_firms_tier'), 'vc_firms', ['tier'], unique=False)
    op.create_table('weekly_briefings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_starting', sa.Date(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('top_regulatory_changes', sa.JSON(), nullable=True),
    sa.Column('top_ma_activity', sa.JSON(), nullable=True),
    sa.Column('emerging_trends', sa.JSON(), nullable=True),
    sa.Column('thesis_implications', sa.Text(), nullable=True),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('certification_type', sa.String(length=100), nullable=True),
    sa.Column('certification_number', sa.String(length=255), nullable=True),
    sa.Column('issuing_body', sa.String(length=255), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_company_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_company_id'], ['tracked_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_documents_tracked_company_id'), 'company_documents', ['tracked_company_id'], unique=False)
    op.create_table('company_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_company_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_company_id'], ['tracked_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_date_severity', 'company_events', ['event_date', 'severity'], unique=False)
    op.create_index(op.f('ix_company_events_event_date'), 'company_events', ['event_date'], unique=False)
    op.create_index(op.f('ix_company_events_event_type'), 'company_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_company_events_severity'), 'company_events', ['severity'], unique=False)
    op.create_index(op.f('ix_company_events_tracked_company_id'), 'company_events', ['tracked_company_id'], unique=False)
    op.create_table('company_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_company_id', sa.Integer(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('note_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_company_id'], ['tracked_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_notes_created_at'), 'company_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_company_notes_note_type'), 'company_notes', ['note_type'], unique=False)
    op.create_index(op.f('ix_company_notes_tracked_company_id'), 'company_notes', ['tracked_company_id'], unique=False)
    op.create_table('company_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_a_id', sa.Integer(), nullable=False),
    sa.Column('company_b_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('discovered_via', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_a_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['company_b_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consolidators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('pe_sponsor_id', sa.Integer(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=True),
    sa.Column('sector_focus', sa.String(length=100), nullable=True),
    sa.Column('typical_target_size_min_usd', sa.BigInteger(), nullable=True),
    sa.Column('typical_target_size_max_usd', sa.BigInteger(), nullable=True),
    sa.Column('acquisition_budget_usd', sa.BigInteger(), nullable=True),
    sa.Column('acquisitions_last_12mo', sa.Integer(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('acquisition_page_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pe_sponsor_id'], ['pe_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pe_firm_id', sa.Integer(), nullable=True),
    sa.Column('target_company_name', sa.String(length=255), nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=True),
    sa.Column('deal_date', sa.Date(), nullable=True),
    sa.Column('deal_type', sa.String(length=50), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('closed_date', sa.Date(), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('subsector', sa.String(length=100), nullable=True),
    sa.Column('geography', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('revenue_gbp', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_gbp', sa.BigInteger(), nullable=True),
    sa.Column('enterprise_value_gbp', sa.BigInteger(), nullable=True),
    sa.Column('ev_revenue_multiple', sa.Float(), nullable=True),
    sa.Column('ev_ebitda_multiple', sa.Float(), nullable=True),
    sa.Column('equity_investment_gbp', sa.BigInteger(), nullable=True),
    sa.Column('debt_gbp', sa.BigInteger(), nullable=True),
    sa.Column('equity_percentage', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Integer(), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), nullable=True),
    sa.Column('enrichment_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pe_firm_id'], ['pe_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deal_ev_range', 'deal_records', ['enterprise_value_gbp'], unique=False)
    op.create_index('idx_deal_sector_date', 'deal_records', ['sector', 'deal_date'], unique=False)
    op.create_index(op.f('ix_deal_records_deal_date'), 'deal_records', ['deal_date'], unique=False)
    op.create_index(op.f('ix_deal_records_geography'), 'deal_records', ['geography'], unique=False)
    op.create_index(op.f('ix_deal_records_pe_firm_id'), 'deal_records', ['pe_firm_id'], unique=False)
    op.create_index(op.f('ix_deal_records_sector'), 'deal_records', ['sector'], unique=False)
    op.create_index(op.f('ix_deal_records_target_company_id'), 'deal_records', ['target_company_id'], unique=False)
    op.create_table('detected_changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('change_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('diff_content', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('divisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('division_name', sa.String(length=255), nullable=False),
    sa.Column('legal_entity', sa.String(length=255), nullable=True),
    sa.Column('companies_house_number', sa.String(length=50), nullable=True),
    sa.Column('revenue_eur', sa.BigInteger(), nullable=True),
    sa.Column('revenue_gbp', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_eur', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_gbp', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_margin', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('employees', sa.Integer(), nullable=True),
    sa.Column('percent_of_parent_revenue', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('hq_location', sa.String(length=255), nullable=True),
    sa.Column('business_description', sa.Text(), nullable=True),
    sa.Column('autonomy_level', sa.String(length=20), nullable=True),
    sa.Column('strategic_autonomy', sa.String(length=20), nullable=True),
    sa.Column('moat_type', sa.String(length=50), nullable=True),
    sa.Column('moat_strength', sa.Integer(), nullable=True),
    sa.Column('market_share', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('competitor_count', sa.Integer(), nullable=True),
    sa.Column('market_growth_rate', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('carveout_probability', sa.Integer(), nullable=True),
    sa.Column('carveout_timeline', sa.String(length=50), nullable=True),
    sa.Column('attractiveness_score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['corporate_parents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_carveout_probability', 'divisions', ['carveout_probability'], unique=False, mysql_length=None)
    op.create_index('idx_attractiveness_score', 'divisions', ['attractiveness_score'], unique=False, mysql_length=None)
    op.create_table('intelligence_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('implications', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_hash')
    )
    op.create_index(op.f('ix_intelligence_items_category'), 'intelligence_items', ['category'], unique=False)
    op.create_index(op.f('ix_intelligence_items_published_date'), 'intelligence_items', ['published_date'], unique=False)
    op.create_index(op.f('ix_intelligence_items_relevance_score'), 'intelligence_items', ['relevance_score'], unique=False)
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=50), nullable=False),
    sa.Column('interaction_date', sa.Date(), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=20), nullable=True),
    sa.Column('next_action', sa.String(length=500), nullable=True),
    sa.Column('next_action_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_interaction_date', 'interactions', ['interaction_date'], unique=False)
    op.create_index('idx_interaction_type', 'interactions', ['interaction_type'], unique=False)
    op.create_index(op.f('ix_interactions_contact_id'), 'interactions', ['contact_id'], unique=False)
    op.create_table('network_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_a_id', sa.Integer(), nullable=False),
    sa.Column('contact_b_id', sa.Integer(), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('discovered_via', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('contact_a_id != contact_b_id', name='no_self_connection'),
    sa.CheckConstraint('strength >= 0 AND strength <= 100', name='strength_range'),
    sa.ForeignKeyConstraint(['contact_a_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['contact_b_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_network_contacts', 'network_connections', ['contact_a_id', 'contact_b_id'], unique=False)
    op.create_index(op.f('ix_network_connections_contact_a_id'), 'network_connections', ['contact_a_id'], unique=False)
    op.create_index(op.f('ix_network_connections_contact_b_id'), 'network_connections', ['contact_b_id'], unique=False)
    op.create_table('pe_investments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pe_firm_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=True),
    sa.Column('exit_date', sa.Date(), nullable=True),
    sa.Column('is_exited', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('investment_year', sa.Integer(), nullable=True),
    sa.Column('exit_year', sa.Integer(), nullable=True),
    sa.Column('entry_valuation_usd', sa.BigInteger(), nullable=True),
    sa.Column('entry_multiple', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('exit_valuation_usd', sa.BigInteger(), nullable=True),
    sa.Column('exit_multiple', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('moic', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('irr', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('moat_type', sa.String(length=50), nullable=True),
    sa.Column('investment_thesis', sa.Text(), nullable=True),
    sa.Column('deal_announcement_url', sa.String(length=500), nullable=True),
    sa.Column('exit_thesis', sa.Text(), nullable=True),
    sa.Column('strategic_rationale', sa.Text(), nullable=True),
    sa.Column('pe_identified_moats', sa.JSON(), nullable=True),
    sa.Column('thesis_keywords', sa.JSON(), nullable=True),
    sa.Column('is_enriched', sa.Boolean(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pe_firm_id'], ['pe_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pe_inv_entry_date', 'pe_investments', ['entry_date'], unique=False)
    op.create_index('idx_pe_inv_moat', 'pe_investments', ['moat_type'], unique=False)
    op.create_index(op.f('ix_pe_investments_company_id'), 'pe_investments', ['company_id'], unique=False)
    op.create_table('price_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('plan_name', sa.String(length=100), nullable=True),
    sa.Column('price_amount', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('billing_period', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['target_id'], ['monitoring_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('strategic_acquisitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acquirer_id', sa.Integer(), nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=True),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('purchase_price_usd', sa.BigInteger(), nullable=True),
    sa.Column('target_revenue_usd', sa.BigInteger(), nullable=True),
    sa.Column('target_ebitda_usd', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_multiple', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('strategic_rationale', sa.Text(), nullable=True),
    sa.Column('target_moat_type', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acquirer_id'], ['strategic_acquirers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracking_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_company_id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_company_id'], ['tracked_companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alert_unread', 'tracking_alerts', ['is_read', 'created_at'], unique=False)
    op.create_index(op.f('ix_tracking_alerts_created_at'), 'tracking_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_tracking_alerts_is_read'), 'tracking_alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_tracking_alerts_tracked_company_id'), 'tracking_alerts', ['tracked_company_id'], unique=False)
    op.create_table('vc_announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vc_firm_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('round_type', sa.String(length=50), nullable=True),
    sa.Column('amount_gbp', sa.Integer(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('linkedin_post_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['vc_firm_id'], ['vc_firms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vc_announcements_announced_date'), 'vc_announcements', ['announced_date'], unique=False)
    op.create_table('carveout_processes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('announced_date', sa.Date(), nullable=True),
    sa.Column('expected_close_date', sa.Date(), nullable=True),
    sa.Column('actual_close_date', sa.Date(), nullable=True),
    sa.Column('process_type', sa.String(length=50), nullable=True),
    sa.Column('banker', sa.String(length=255), nullable=True),
    sa.Column('estimated_valuation_eur', sa.BigInteger(), nullable=True),
    sa.Column('estimated_multiple', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('buyer', sa.String(length=255), nullable=True),
    sa.Column('final_price_eur', sa.BigInteger(), nullable=True),
    sa.Column('final_multiple', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('process_status', sa.String(length=50), nullable=True),
    sa.Column('fund_participated', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carveout_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=True),
    sa.Column('signal_type', sa.String(length=50), nullable=True),
    sa.Column('signal_category', sa.String(length=100), nullable=True),
    sa.Column('signal_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('increases_probability', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['division_id'], ['divisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consolidator_acquisitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('consolidator_id', sa.Integer(), nullable=False),
    sa.Column('target_company_id', sa.Integer(), nullable=True),
    sa.Column('target_name', sa.String(length=255), nullable=False),
    sa.Column('announcement_date', sa.Date(), nullable=True),
    sa.Column('close_date', sa.Date(), nullable=True),
    sa.Column('purchase_price_usd', sa.BigInteger(), nullable=True),
    sa.Column('target_revenue_usd', sa.BigInteger(), nullable=True),
    sa.Column('target_ebitda_usd', sa.BigInteger(), nullable=True),
    sa.Column('ebitda_multiple', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.Column('is_platform', sa.Boolean(), nullable=True),
    sa.Column('platform_number', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['consolidator_id'], ['consolidators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_comparables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deal_record_id', sa.Integer(), nullable=False),
    sa.Column('comparable_deal_id', sa.Integer(), nullable=False),
    sa.Column('similarity_score', sa.Integer(), nullable=True),
    sa.Column('similarity_reasons', sa.JSON(), nullable=True),
    sa.Column('sector_similarity', sa.Float(), nullable=True),
    sa.Column('size_similarity', sa.Float(), nullable=True),
    sa.Column('geography_similarity', sa.Float(), nullable=True),
    sa.Column('time_similarity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comparable_deal_id'], ['deal_records.id'], ),
    sa.ForeignKeyConstraint(['deal_record_id'], ['deal_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comparable_pair', 'deal_comparables', ['deal_record_id', 'comparable_deal_id'], unique=True)
    op.create_index(op.f('ix_deal_comparables_comparable_deal_id'), 'deal_comparables', ['comparable_deal_id'], unique=False)
    op.create_index(op.f('ix_deal_comparables_deal_record_id'), 'deal_comparables', ['deal_record_id'], unique=False)
    op.create_table('threat_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('threat_score', sa.Integer(), nullable=True),
    sa.Column('threat_level', sa.String(length=20), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['announcement_id'], ['vc_announcements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scores_threat_level'), 'threat_scores', ['threat_level'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_scores_threat_level'), table_name='threat_scores')
    op.drop_table('threat_scores')
    op.drop_index(op.f('ix_deal_comparables_deal_record_id'), table_name='deal_comparables')
    op.drop_index(op.f('ix_deal_comparables_comparable_deal_id'), table_name='deal_comparables')
    op.drop_index('idx_comparable_pair', table_name='deal_comparables')
    op.drop_table('deal_comparables')
    op.drop_table('consolidator_acquisitions')
    op.drop_table('carveout_signals')
    op.drop_table('carveout_processes')
    op.drop_index(op.f('ix_vc_announcements_announced_date'), table_name='vc_announcements')
    op.drop_table('vc_announcements')
    op.drop_index(op.f('ix_tracking_alerts_tracked_company_id'), table_name='tracking_alerts')
    op.drop_index(op.f('ix_tracking_alerts_is_read'), table_name='tracking_alerts')
    op.drop_index(op.f('ix_tracking_alerts_created_at'), table_name='tracking_alerts')
    op.drop_index('idx_alert_unread', table_name='tracking_alerts')
    op.drop_table('tracking_alerts')
    op.drop_table('strategic_acquisitions')
    op.drop_table('price_points')
    op.drop_index(op.f('ix_pe_investments_company_id'), table_name='pe_investments')
    op.drop_index('idx_pe_inv_moat', table_name='pe_investments')
    op.drop_index('idx_pe_inv_entry_date', table_name='pe_investments')
    op.drop_table('pe_investments')
    op.drop_index(op.f('ix_network_connections_contact_b_id'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_contact_a_id'), table_name='network_connections')
    op.drop_index('idx_network_contacts', table_name='network_connections')
    op.drop_table('network_connections')
    op.drop_index(op.f('ix_interactions_contact_id'), table_name='interactions')
    op.drop_index('idx_interaction_type', table_name='interactions')
    op.drop_index('idx_interaction_date', table_name='interactions')
    op.drop_table('interactions')
    op.drop_index(op.f('ix_intelligence_items_relevance_score'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_published_date'), table_name='intelligence_items')
    op.drop_index(op.f('ix_intelligence_items_category'), table_name='intelligence_items')
    op.drop_table('intelligence_items')
    op.drop_index('idx_attractiveness_score', table_name='divisions', mysql_length=None)
    op.drop_index('idx_carveout_probability', table_name='divisions', mysql_length=None)
    op.drop_table('divisions')
    op.drop_table('detected_changes')
    op.drop_index(op.f('ix_deal_records_target_company_id'), table_name='deal_records')
    op.drop_index(op.f('ix_deal_records_sector'), table_name='deal_records')
    op.drop_index(op.f('ix_deal_records_pe_firm_id'), table_name='deal_records')
    op.drop_index(op.f('ix_deal_records_geography'), table_name='deal_records')
    op.drop_index(op.f('ix_deal_records_deal_date'), table_name='deal_records')
    op.drop_index('idx_deal_sector_date', table_name='deal_records')
    op.drop_index('idx_deal_ev_range', table_name='deal_records')
    op.drop_table('deal_records')
    op.drop_table('consolidators')
    op.drop_table('company_relationships')
    op.drop_index(op.f('ix_company_notes_tracked_company_id'), table_name='company_notes')
    op.drop_index(op.f('ix_company_notes_note_type'), table_name='company_notes')
    op.drop_index(op.f('ix_company_notes_created_at'), table_name='company_notes')
    op.drop_table('company_notes')
    op.drop_index(op.f('ix_company_events_tracked_company_id'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_severity'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_event_type'), table_name='company_events')
    op.drop_index(op.f('ix_company_events_event_date'), table_name='company_events')
    op.drop_index('idx_event_date_severity', table_name='company_events')
    op.drop_table('company_events')
    op.drop_index(op.f('ix_company_documents_tracked_company_id'), table_name='company_documents')
    op.drop_table('company_documents')
    op.drop_table('certifications')
    op.drop_table('weekly_briefings')
    op.drop_index(op.f('ix_vc_firms_tier'), table_name='vc_firms')
    op.drop_table('vc_firms')
    op.drop_index(op.f('ix_tracked_companies_tracking_status'), table_name='tracked_companies')
    op.drop_index(op.f('ix_tracked_companies_priority'), table_name='tracked_companies')
    op.drop_index(op.f('ix_tracked_companies_next_check_due'), table_name='tracked_companies')
    op.drop_index(op.f('ix_tracked_companies_company_id'), table_name='tracked_companies')
    op.drop_index('idx_tracked_status_priority', table_name='tracked_companies')
    op.drop_table('tracked_companies')
    op.drop_index(op.f('ix_strategic_acquirers_name'), table_name='strategic_acquirers')
    op.drop_table('strategic_acquirers')
    op.drop_table('regulatory_changes')
    op.drop_index(op.f('ix_pe_firms_name'), table_name='pe_firms')
    op.drop_table('pe_firms')
    op.drop_table('news_sources')
    op.drop_table('monitoring_targets')
    op.drop_table('market_trends')
    op.drop_index(op.f('ix_market_metrics_time_period'), table_name='market_metrics')
    op.drop_index(op.f('ix_market_metrics_sector'), table_name='market_metrics')
    op.drop_index('idx_metrics_sector_period', table_name='market_metrics')
    op.drop_index('idx_metrics_hot', table_name='market_metrics')
    op.drop_table('market_metrics')
    op.drop_index(op.f('ix_deal_probabilities_target_company_id'), table_name='deal_probabilities')
    op.drop_index('idx_probability_score', table_name='deal_probabilities')
    op.drop_index('idx_probability_company', table_name='deal_probabilities')
    op.drop_table('deal_probabilities')
    op.drop_table('corporate_parents')
    op.drop_index(op.f('ix_contacts_full_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_company_name'), table_name='contacts')
    op.drop_index('idx_contact_type', table_name='contacts')
    op.drop_index('idx_contact_strength', table_name='contacts')
    op.drop_index('idx_contact_company', table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_tier'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_registration_number'), table_name='companies')
    op.drop_index(op.f('ix_companies_moat_score'), table_name='companies')
    op.drop_index(op.f('ix_companies_companies_house_number'), table_name='companies')
    op.drop_index('idx_moat_score_desc', table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_alert_preferences_user_id'), table_name='alert_preferences')
    op.drop_table('alert_preferences')
    # ### end Alembic commands ###
