"""add_capability_tables

Revision ID: 823def1a6467
Revises: d7440c695f76
Create Date: 2026-02-23 22:36:18.135372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823def1a6467'
down_revision: Union[str, Sequence[str], None] = 'd7440c695f76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capability_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('estimated_timeline', sa.String(length=100), nullable=True),
    sa.Column('investment_implication', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_weighted_score', sa.Float(), nullable=False),
    sa.Column('approach_threshold', sa.Float(), nullable=False),
    sa.Column('reached_threshold', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_table('capability_signal_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('signal_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_key')
    )
    op.create_index(op.f('ix_capability_signal_definitions_level'), 'capability_signal_definitions', ['level'], unique=False)
    op.create_table('capability_signal_observations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_key', sa.String(length=100), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('observed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('logged_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_signal_observations_observed_at'), 'capability_signal_observations', ['observed_at'], unique=False)
    op.create_index(op.f('ix_capability_signal_observations_signal_key'), 'capability_signal_observations', ['signal_key'], unique=False)
    op.create_index('ix_capability_signal_observations_signal_observed', 'capability_signal_observations', ['signal_key', 'observed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_capability_signal_observations_signal_observed', table_name='capability_signal_observations')
    op.drop_index(op.f('ix_capability_signal_observations_signal_key'), table_name='capability_signal_observations')
    op.drop_index(op.f('ix_capability_signal_observations_observed_at'), table_name='capability_signal_observations')
    op.drop_table('capability_signal_observations')
    op.drop_index(op.f('ix_capability_signal_definitions_level'), table_name='capability_signal_definitions')
    op.drop_table('capability_signal_definitions')
    op.drop_table('capability_levels')
    # ### end Alembic commands ###
