"""add_scoring_events_audit_table

Revision ID: 994a24fc74ad
Revises: d16997d5768d
Create Date: 2026-02-16 23:02:33.342792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994a24fc74ad'
down_revision: Union[str, Sequence[str], None] = 'd16997d5768d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scoring_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('moat_score', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=False),
    sa.Column('moat_attributes', sa.JSON(), nullable=False),
    sa.Column('weights_used', sa.JSON(), nullable=False),
    sa.Column('previous_score', sa.Integer(), nullable=True),
    sa.Column('score_delta', sa.Integer(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('scored_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scoring_events_company_id'), 'scoring_events', ['company_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scoring_events_company_id'), table_name='scoring_events')
    op.drop_table('scoring_events')
    # ### end Alembic commands ###
