"""Add hq_city and sub_sector to companies

Revision ID: d16997d5768d
Revises: 63855373bde4
Create Date: 2026-02-15 21:52:58.321695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd16997d5768d'
down_revision: Union[str, Sequence[str], None] = '63855373bde4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('hq_city', sa.String(length=100), nullable=True))
    op.add_column('companies', sa.Column('sub_sector', sa.String(length=100), nullable=True))
    op.drop_index(op.f('idx_companies_name'), table_name='companies')
    op.drop_index(op.f('idx_companies_website'), table_name='companies')
    op.create_index(op.f('ix_companies_hq_city'), 'companies', ['hq_city'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_sub_sector'), 'companies', ['sub_sector'], unique=False)
    op.create_index(op.f('ix_companies_website'), 'companies', ['website'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_companies_website'), table_name='companies')
    op.drop_index(op.f('ix_companies_sub_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_hq_city'), table_name='companies')
    op.create_index(op.f('idx_companies_website'), 'companies', ['website'], unique=False)
    op.create_index(op.f('idx_companies_name'), 'companies', ['name'], unique=False)
    op.drop_column('companies', 'sub_sector')
    op.drop_column('companies', 'hq_city')
    # ### end Alembic commands ###
