"""add_canon_tables

Revision ID: d7440c695f76
Revises: b2c3d4e5f6a7
Create Date: 2026-02-23 22:35:21.034386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7440c695f76'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canon_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('field_changed', sa.String(length=100), nullable=False),
    sa.Column('previous_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('source_module', sa.String(length=100), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_canon_entries_company_id'), 'canon_entries', ['company_id'], unique=False)
    op.create_index(op.f('ix_canon_entries_created_at'), 'canon_entries', ['created_at'], unique=False)
    op.create_table('company_canons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('current_tier', sa.String(length=10), nullable=True),
    sa.Column('thesis_summary', sa.Text(), nullable=True),
    sa.Column('moat_assessment', sa.JSON(), nullable=True),
    sa.Column('open_questions', sa.JSON(), nullable=True),
    sa.Column('coverage_status', sa.String(length=20), nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_canons_company_id'), 'company_canons', ['company_id'], unique=True)
    op.create_table('moat_score_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('pillar', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_moat_score_history_company_pillar_created', 'moat_score_history', ['company_id', 'pillar', 'created_at'], unique=False)
    op.create_index(op.f('ix_moat_score_history_company_id'), 'moat_score_history', ['company_id'], unique=False)
    op.create_index(op.f('ix_moat_score_history_created_at'), 'moat_score_history', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_moat_score_history_created_at'), table_name='moat_score_history')
    op.drop_index(op.f('ix_moat_score_history_company_id'), table_name='moat_score_history')
    op.drop_index('idx_moat_score_history_company_pillar_created', table_name='moat_score_history')
    op.drop_table('moat_score_history')
    op.drop_index(op.f('ix_company_canons_company_id'), table_name='company_canons')
    op.drop_table('company_canons')
    op.drop_index(op.f('ix_canon_entries_created_at'), table_name='canon_entries')
    op.drop_index(op.f('ix_canon_entries_company_id'), table_name='canon_entries')
    op.drop_table('canon_entries')
    # ### end Alembic commands ###
