"""add_resilience_tables

Revision ID: e661f8adf73e
Revises: a054567d313e
Create Date: 2026-02-23 22:51:34.219051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e661f8adf73e'
down_revision: Union[str, Sequence[str], None] = 'a054567d313e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_resilience_assessments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('capability_level', sa.Integer(), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('substitution_score', sa.Integer(), nullable=True),
    sa.Column('disintermediation_score', sa.Integer(), nullable=True),
    sa.Column('amplification_score', sa.Integer(), nullable=True),
    sa.Column('cost_disruption_score', sa.Integer(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=True),
    sa.Column('overall_verdict', sa.String(length=20), nullable=True),
    sa.Column('scarcity_classification', sa.String(length=50), nullable=True),
    sa.Column('scarcity_rationale', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=20), server_default='manual', nullable=False),
    sa.Column('llm_prompt_version', sa.String(length=20), nullable=True),
    sa.Column('raw_llm_response', sa.Text(), nullable=True),
    sa.Column('assessment_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_ai_resilience_company_level_assessed', 'ai_resilience_assessments', ['company_id', 'capability_level', 'assessed_at'], unique=False)
    op.create_index(op.f('ix_ai_resilience_assessments_assessed_at'), 'ai_resilience_assessments', ['assessed_at'], unique=False)
    op.create_index(op.f('ix_ai_resilience_assessments_company_id'), 'ai_resilience_assessments', ['company_id'], unique=False)
    op.create_table('ai_resilience_flags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('capability_level', sa.Integer(), nullable=False),
    sa.Column('previous_verdict', sa.String(length=20), nullable=True),
    sa.Column('new_verdict', sa.String(length=20), nullable=False),
    sa.Column('composite_delta', sa.Float(), nullable=True),
    sa.Column('flag_reason', sa.Text(), nullable=True),
    sa.Column('reviewed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_resilience_flags_company_id'), 'ai_resilience_flags', ['company_id'], unique=False)
    op.create_index(op.f('ix_ai_resilience_flags_created_at'), 'ai_resilience_flags', ['created_at'], unique=False)
    op.create_index(op.f('ix_ai_resilience_flags_reviewed'), 'ai_resilience_flags', ['reviewed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_resilience_flags_reviewed'), table_name='ai_resilience_flags')
    op.drop_index(op.f('ix_ai_resilience_flags_created_at'), table_name='ai_resilience_flags')
    op.drop_index(op.f('ix_ai_resilience_flags_company_id'), table_name='ai_resilience_flags')
    op.drop_table('ai_resilience_flags')
    op.drop_index(op.f('ix_ai_resilience_assessments_company_id'), table_name='ai_resilience_assessments')
    op.drop_index(op.f('ix_ai_resilience_assessments_assessed_at'), table_name='ai_resilience_assessments')
    op.drop_index('idx_ai_resilience_company_level_assessed', table_name='ai_resilience_assessments')
    op.drop_table('ai_resilience_assessments')
    # ### end Alembic commands ###
